<?php

/**
 * PluginTimelineLikeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTimelineLikeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTimelineLikeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTimelineLike');
    }
}